name: Build & Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: make build
      
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/*"   
