name: Build & Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    
    - name: Build
      run: make build
      
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${SHORT_SHA}
        artifacts: "bin/**"   
